version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name Lastwork-CodeDeploy --s3-location s3://lastworks3/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src